<?php 
if( function_exists('acf_add_local_field_group') ):
	
	acf_add_local_field_group(array(
		'key' => 'group_62408f34c21ec',
		'title' => 'Staff Profile',
		'fields' => array(
			array(
				'key' => 'field_62408f41bb140',
				'label' => 'Profile Picture',
				'name' => 'profile_picture',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_62408f5bbb141',
				'label' => 'First Name',
				'name' => 'first_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_624092da95009',
				'label' => 'Last Name',
				'name' => 'last_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6240908efd25e',
				'label' => 'Position Title',
				'name' => 'position_title',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'lifeguard' => 'Life Guard',
					'deck-leader' => 'Deck Leader',
					'pool-manage' => 'Pool Manager',
					'cpo' => 'CPO',
					'swim-coach' => 'Coach (Swim)',
					'dive-coach' => 'Coach (Dive)',
					'proshop' => 'Pro-Shop Staff',
					'coach' => 'Coach',
					'assistant-pro' => 'Assistant Tennis Pro',
					'tennis-pro' => 'Tennis Pro',
					'club-manager' => 'Club Manager',
					'accountant' => 'Accountant',
					'groundskeeper' => 'Grounds Keeper',
					'maintenance' => 'Maintenance',
				),
				'default_value' => array(
				),
				'allow_null' => 0,
				'multiple' => 1,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'label',
				'placeholder' => '',
			),
			array(
				'key' => 'field_62408f72bb142',
				'label' => 'Date Started',
				'name' => 'date_started',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_62409006bb146',
				'label' => 'Birthday',
				'name' => 'birthday',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'd/m/Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_6240900ebb147',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62409015bb148',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_62408f88bb143',
				'label' => 'Biography',
				'name' => 'biography',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_6240901abb149',
				'label' => 'Social Media',
				'name' => 'social_media',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_6240902cbb14a',
						'label' => 'Icon',
						'name' => 'icon',
						'type' => 'font-awesome',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'icon_sets' => array(
							0 => 'solid',
							1 => 'regular',
							2 => 'brands',
						),
						'custom_icon_set' => '',
						'default_label' => '&lt;i class="fa-brands fa-facebook fa-fw"&gt;&lt;/i&gt; Facebook',
						'default_value' => '{ "style" : "brands", "id" : "facebook", "label" : "Facebook", "unicode" : "f09a" }',
						'save_format' => 'class',
						'allow_null' => 0,
						'show_preview' => 0,
						'enqueue_fa' => 0,
						'fa_live_preview' => '',
						'choices' => array(
						),
					),
					array(
						'key' => 'field_6240903bbb14b',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'staff_profile',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'slug',
			5 => 'author',
			6 => 'format',
			7 => 'featured_image',
			8 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
	
	endif;		